# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

superSplit <- function(str, sep = ' ') {
    .Call('_superml_superSplit', PACKAGE = 'superml', str, sep)
}

superNgrams <- function(str, ngram_range, sep) {
    .Call('_superml_superNgrams', PACKAGE = 'superml', str, ngram_range, sep)
}

superTokenizer <- function(string) {
    .Call('_superml_superTokenizer', PACKAGE = 'superml', string)
}

superCountMatrix <- function(sent, tokens) {
    .Call('_superml_superCountMatrix', PACKAGE = 'superml', sent, tokens)
}

